import { Achievement, VoyageHistoryEntry } from '@/types';

export const achievementDefinitions: Achievement[] = [
  {
    id: 'ach-first-voyage',
    name: 'First Voyage',
    description: 'Complete your first voyage.',
    emoji: '⛵',
    category: 'voyage',
    requirement: 'Complete 1 voyage',
    unlockedAt: '2026-08-27T12:00:00Z',
  },
  {
    id: 'ach-first-crew',
    name: 'First Crew Member',
    description: 'Bring your first sailor aboard.',
    emoji: '⚓',
    category: 'crew',
    requirement: 'Add 1 crew member',
    unlockedAt: '2026-08-27T12:30:00Z',
  },
  {
    id: 'ach-seven-seas',
    name: 'Seven Seas',
    description: 'Complete seven voyages.',
    emoji: '🌊',
    category: 'voyage',
    requirement: 'Complete 7 voyages',
    unlockedAt: '2026-08-27T14:00:00Z',
  },
  {
    id: 'ach-bottle-collector',
    name: 'Bottle Collector',
    description: 'Receive 5 messages in a bottle.',
    emoji: '📨',
    category: 'bottle',
    requirement: 'Receive 5 bottles',
    unlockedAt: null,
  },
  {
    id: 'ach-world-sailor',
    name: 'World Sailor',
    description: 'Meet sailors from 10 different countries.',
    emoji: '🌎',
    category: 'world',
    requirement: 'Meet 10 countries',
    unlockedAt: null,
  },
  {
    id: 'ach-old-salt',
    name: 'Old Salt',
    description: 'Complete 50 voyages. You\'re a seasoned sailor.',
    emoji: '🧭',
    category: 'special',
    requirement: 'Complete 50 voyages',
    unlockedAt: null,
  },
  {
    id: 'ach-island-hopper',
    name: 'Island Hopper',
    description: 'Visit 5 different islands.',
    emoji: '🏝️',
    category: 'island',
    requirement: 'Visit 5 islands',
    unlockedAt: null,
  },
  {
    id: 'ach-night-owl',
    name: 'Night Owl',
    description: 'Have a conversation after midnight.',
    emoji: '🌙',
    category: 'special',
    requirement: 'Chat after midnight',
    unlockedAt: '2026-08-27T00:30:00Z',
  },
];

export const mockVoyageHistory: VoyageHistoryEntry[] = [
  {
    id: 'vh-001',
    voyageId: 'v-001',
    type: 'random',
    islandName: null,
    metSailorName: 'Luna',
    metSailorCountry: 'Japan',
    metSailorFlag: '🇯🇵',
    broughtAboard: true,
    date: '2026-08-27T12:00:00Z',
  },
  {
    id: 'vh-002',
    voyageId: 'v-002',
    type: 'island',
    islandName: 'Music Island',
    metSailorName: 'Mika',
    metSailorCountry: 'Finland',
    metSailorFlag: '🇫🇮',
    broughtAboard: true,
    date: '2026-08-26T18:00:00Z',
  },
  {
    id: 'vh-003',
    voyageId: 'v-003',
    type: 'random',
    islandName: null,
    metSailorName: 'Alex',
    metSailorCountry: 'Brazil',
    metSailorFlag: '🇧🇷',
    broughtAboard: true,
    date: '2026-08-25T15:00:00Z',
  },
  {
    id: 'vh-004',
    voyageId: 'v-004',
    type: 'island',
    islandName: 'Deep Talk Island',
    metSailorName: 'Noor',
    metSailorCountry: 'Morocco',
    metSailorFlag: '🇲🇦',
    broughtAboard: false,
    date: '2026-08-24T22:00:00Z',
  },
  {
    id: 'vh-005',
    voyageId: 'v-005',
    type: 'random',
    islandName: null,
    metSailorName: 'Kai',
    metSailorCountry: 'New Zealand',
    metSailorFlag: '🇳🇿',
    broughtAboard: false,
    date: '2026-08-23T11:00:00Z',
  },
  {
    id: 'vh-006',
    voyageId: 'v-006',
    type: 'island',
    islandName: 'Gaming Island',
    metSailorName: 'Yuki',
    metSailorCountry: 'South Korea',
    metSailorFlag: '🇰🇷',
    broughtAboard: false,
    date: '2026-08-22T16:00:00Z',
  },
  {
    id: 'vh-007',
    voyageId: 'v-007',
    type: 'random',
    islandName: null,
    metSailorName: 'River',
    metSailorCountry: 'Canada',
    metSailorFlag: '🇨🇦',
    broughtAboard: false,
    date: '2026-08-21T09:00:00Z',
  },
];
