import { Island } from '@/types';

export const mockIslands: Island[] = [
  {
    id: 'island-midnight',
    name: 'Midnight Island',
    emoji: '🌙',
    theme: 'Late night conversations',
    description: 'For sailors who aren\'t ready to sleep.',
    longDescription: 'A quiet island where night owls gather. The conversations here are often more honest, more personal. There\'s something about the late hours that makes people open up.',
    activeSailors: 128,
    color: '#1D144D',
    gradientFrom: '#1D144D',
    gradientTo: '#503599',
  },
  {
    id: 'island-music',
    name: 'Music Island',
    emoji: '🎵',
    theme: 'Share songs and talk about music',
    description: 'Share songs, discover sounds, talk rhythm.',
    longDescription: 'An island where every conversation has a soundtrack. Share your favorite songs, discover new artists, and connect over the music that moves you.',
    activeSailors: 256,
    color: '#F06449',
    gradientFrom: '#F06449',
    gradientTo: '#FF7F67',
  },
  {
    id: 'island-deeptalk',
    name: 'Deep Talk Island',
    emoji: '🌊',
    theme: 'Longer, meaningful conversations',
    description: 'No small talk. Real conversations only.',
    longDescription: 'This island is for people who want more than surface-level chat. Expect longer conversations about life, ideas, dreams, and everything in between.',
    activeSailors: 89,
    color: '#2B7DE9',
    gradientFrom: '#174A8F',
    gradientTo: '#2B7DE9',
  },
  {
    id: 'island-gaming',
    name: 'Gaming Island',
    emoji: '🎮',
    theme: 'Games and gaming conversations',
    description: 'Find your next co-op partner.',
    longDescription: 'Whether you\'re into indie games, competitive esports, or retro classics — this is where gamers meet, share recommendations, and find people to play with.',
    activeSailors: 342,
    color: '#2BB89A',
    gradientFrom: '#1A6E5D',
    gradientTo: '#43D7AF',
  },
  {
    id: 'island-world',
    name: 'Around the World',
    emoji: '🌍',
    theme: 'Meet people from different countries',
    description: 'Every conversation crosses a border.',
    longDescription: 'Travel the world without leaving your seat. Meet people from different cultures, learn about life in other countries, and broaden your horizons.',
    activeSailors: 198,
    color: '#E6BF00',
    gradientFrom: '#B39600',
    gradientTo: '#FFD633',
  },
  {
    id: 'island-random',
    name: 'Random Island',
    emoji: '🎲',
    theme: 'Completely unpredictable conversations',
    description: 'You never know what you\'ll find here.',
    longDescription: 'The wildcard island. No theme, no rules, no expectations. Just pure unpredictable conversations with whoever happens to wash ashore.',
    activeSailors: 156,
    color: '#8760E6',
    gradientFrom: '#6B47BF',
    gradientTo: '#9F7FF7',
  },
];
