import { SailorProfile } from '@/types';

export const mockSailors: SailorProfile[] = [
  {
    userId: 'sailor-001',
    sailorName: 'Luna',
    country: 'Japan',
    countryFlag: '🇯🇵',
    languages: ['Japanese', 'English'],
    interests: ['Music', 'Books', 'Night owl', 'Photography'],
    bio: 'I collect strange postcards.',
    conversationPreferences: ['deep', 'creative'],
    isAnonymous: false,
    avatarColor: '#9F7FF7',
    createdAt: '2026-07-15T10:00:00Z',
  },
  {
    userId: 'sailor-002',
    sailorName: 'Mika',
    country: 'Finland',
    countryFlag: '🇫🇮',
    languages: ['Finnish', 'English', 'Swedish'],
    interests: ['Nature', 'Gaming', 'Coffee', 'Northern Lights'],
    bio: 'Happiest when it snows.',
    conversationPreferences: ['casual', 'funny'],
    isAnonymous: false,
    avatarColor: '#43D7AF',
    createdAt: '2026-06-20T10:00:00Z',
  },
  {
    userId: 'sailor-003',
    sailorName: 'Alex',
    country: 'Brazil',
    countryFlag: '🇧🇷',
    languages: ['Portuguese', 'English', 'Spanish'],
    interests: ['Football', 'Cooking', 'Music', 'Travel'],
    bio: 'What\'s one thing you want to accomplish this year?',
    conversationPreferences: ['casual', 'supportive'],
    isAnonymous: false,
    avatarColor: '#FFD633',
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    userId: 'sailor-004',
    sailorName: 'Noor',
    country: 'Morocco',
    countryFlag: '🇲🇦',
    languages: ['Arabic', 'French', 'English'],
    interests: ['Art', 'Philosophy', 'Tea', 'Stars'],
    bio: 'I think the night sky tells stories.',
    conversationPreferences: ['deep', 'philosophical'],
    isAnonymous: false,
    avatarColor: '#2B7DE9',
    createdAt: '2026-05-10T10:00:00Z',
  },
  {
    userId: 'sailor-005',
    sailorName: 'Kai',
    country: 'New Zealand',
    countryFlag: '🇳🇿',
    languages: ['English', 'Māori'],
    interests: ['Surfing', 'Hiking', 'Dogs', 'Sunsets'],
    bio: 'Life is better near the ocean.',
    conversationPreferences: ['casual', 'funny', 'supportive'],
    isAnonymous: false,
    avatarColor: '#F06449',
    createdAt: '2026-04-25T10:00:00Z',
  },
  {
    userId: 'sailor-006',
    sailorName: 'Yuki',
    country: 'South Korea',
    countryFlag: '🇰🇷',
    languages: ['Korean', 'English'],
    interests: ['Anime', 'Drawing', 'K-pop', 'Cats'],
    bio: 'Currently learning to draw whales.',
    conversationPreferences: ['creative', 'casual'],
    isAnonymous: false,
    avatarColor: '#FF7F67',
    createdAt: '2026-07-01T10:00:00Z',
  },
  {
    userId: 'sailor-007',
    sailorName: 'River',
    country: 'Canada',
    countryFlag: '🇨🇦',
    languages: ['English', 'French'],
    interests: ['Reading', 'Camping', 'Astronomy', 'Piano'],
    bio: 'Always looking for the next great book.',
    conversationPreferences: ['deep', 'philosophical', 'creative'],
    isAnonymous: false,
    avatarColor: '#8760E6',
    createdAt: '2026-03-15T10:00:00Z',
  },
];

export const currentUserProfile: SailorProfile = {
  userId: 'current-user',
  sailorName: 'You',
  country: 'India',
  countryFlag: '🇮🇳',
  languages: ['English', 'Hindi'],
  interests: ['Technology', 'Music', 'Travel', 'Books'],
  bio: 'Just starting my voyage.',
  conversationPreferences: ['casual', 'deep'],
  isAnonymous: false,
  avatarColor: '#2B7DE9',
  createdAt: '2026-08-27T10:00:00Z',
};
